{% set name = "raven-wps" %}
{% set version = "0.18.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Ouranosinc/raven/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1429dcf77aaf1fedb6e5166b9c324a111310f529d5f5a69f8359f4a74286d810

build:
  number: 1
#  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - raven-wps=raven.cli:cli
  script_env:
    - CONDA_BUILD

requirements:
  host:
    - python
    - pip
    - flit
  run:
    - python
    - pip
    - click
    - jinja2
    - matplotlib-base
    - netCDF4
    - numpy
    - owslib <0.29
    - pandas <2.0  # [py==38]
    - pandas  # [py>=39]
    - psutil
    - pywps ==4.5.1
    - requests
    - xarray >=0.18
    - xclim >=0.31.0
    # GIS libraries
    - affine
    - fiona >=1.9.0,<2.0
    - geojson
    - geopandas
    - pyogrio
    - pyproj >=3.4
    - pysheds
    - rasterio
    - rasterstats
    - rioxarray
    - shapely
    # Docs and other utilities
    - fsspec
    - psycopg2 # to use postgres to log pywps requests like in Prod
    - pymetalink
    - unidecode

# TODO: We need more tests here
test:
  requires:
    - make
    - pip
    - pytest-json-report # Added due to a packaging bug with ESMPy. See: https://github.com/esmf-org/esmf/issues/115
  source_files:
    - Makefile
  commands:
    - pip check
    - make start
    - sleep 2s
    - make stop

about:
  home: https://github.com/Ouranosinc/raven
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An open source server project offering hydrological modeling and analysis capabilities through the Web Processing Service (WPS) standard
  description: |
    Raven is a server providing access to hydrological modeling and analysis
    through the Web Processing Service (WPS) standard. It was made to help
    hydrologists work with climate data and automate some of the tedious work
    required to calibrate and run hydrological models. Its modeling engine is
    the Raven hydrological modeling framework, which can emulate a variety of
    lumped and distributed models.
  doc_url: https://pavics-sdi.readthedocs.io/projects/raven/en/latest/
  dev_url: https://github.com/Ouranosinc/raven

extra:
  recipe-maintainers:
    - Zeitsperre
    - cjauvin
    - huard
