{% set name = "raven-wps" %}
{% set version = "0.17.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Ouranosinc/raven/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7945db3b0de922c31ca5a8d5712b36470d3e205910ea77aef436f5b40583eb3f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - raven-wps=raven.cli:cli
  script_env:
    - CONDA_BUILD

requirements:
  host:
    - python >=3.8
    - numpy >=1.20
    - gdal >=3.0
    - pip
  run:
    - python >=3.8
    - raven-hydro ==3.6
    - ostrich ==21.03.16
    - ravenpy >=0.11.0
    - pywps ==4.5.1
    - affine
    - cartopy
    - click
    - dask
    - fiona >=1.9,<2.0
    - gdal >=3.0
    - geopandas
    - geojson
    - ipyleaflet
    - jinja2
    - matplotlib-base
    - nbval
    - numpy
    - owslib
    - pandas
    - poppler
    - psutil
    - psycopg2
    - pymetalink
    - pyproj >=3.4
    - pysheds
    - rasterio
    - rasterstats
    - rioxarray
    - rtree
    - scipy
    - setuptools
    - shapely
    - spotpy
    - statsmodels
    - tbb
    - unidecode
    - urlpath
    - xarray >=0.18
    - xclim >=0.31.0
    - xskillscore
    - pip

# TODO: We need more tests here
test:
  requires:
    - make
    - pip
    - pytest-json-report # Added due to a packaging bug with ESMPy. See: https://github.com/esmf-org/esmf/issues/115
  source_files:
    - Makefile
  commands:
    - pip check
    - make start
    - sleep 2s
    - make stop

about:
  home: https://github.com/Ouranosinc/raven
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An open source server project offering hydrological modeling and analysis capabilities through the Web Processing Service (WPS) standard
  description: |
    Raven is a server providing access to hydrological modeling and analysis
    through the Web Processing Service (WPS) standard. It was made to help
    hydrologists work with climate data and automate some of the tedious work
    required to calibrate and run hydrological models. Its modeling engine is
    the Raven hydrological modeling framework, which can emulate a variety of
    lumped and distributed models.
  doc_url: https://pavics-sdi.readthedocs.io/projects/raven/en/latest/
  dev_url: https://github.com/Ouranosinc/raven

extra:
  recipe-maintainers:
    - Zeitsperre
    - cjauvin
    - huard
